// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkRuyV8twHDOXYoZYhChwcvpv6hEFwX6M',
    appId: '1:824607952197:web:5ccf1835e7640d6fdf022c',
    messagingSenderId: '824607952197',
    projectId: 'my-portfolio-24cf6',
    authDomain: 'my-portfolio-24cf6.firebaseapp.com',
    storageBucket: 'my-portfolio-24cf6.firebasestorage.app',
    measurementId: 'G-MPMPYNGNR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaNfqteJPGBdsV1NpZXSkxbkurxHDGcvM',
    appId: '1:824607952197:android:9699c1e17a13e377df022c',
    messagingSenderId: '824607952197',
    projectId: 'my-portfolio-24cf6',
    storageBucket: 'my-portfolio-24cf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC91VTPeRG-njtpVBRezBUbtmABQjzk78',
    appId: '1:824607952197:ios:eccc3e7cc03a19acdf022c',
    messagingSenderId: '824607952197',
    projectId: 'my-portfolio-24cf6',
    storageBucket: 'my-portfolio-24cf6.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkRuyV8twHDOXYoZYhChwcvpv6hEFwX6M',
    appId: '1:824607952197:web:65521ac64b4a27c8df022c',
    messagingSenderId: '824607952197',
    projectId: 'my-portfolio-24cf6',
    authDomain: 'my-portfolio-24cf6.firebaseapp.com',
    storageBucket: 'my-portfolio-24cf6.firebasestorage.app',
    measurementId: 'G-0T8DMPR0FC',
  );
}
