// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjAD9heDAoOXO9MfrT9TePQM0Pya5bunI',
    appId: '1:83503088349:web:7a23895eff51ef2e91d134',
    messagingSenderId: '83503088349',
    projectId: 'saddam-khoso',
    authDomain: 'saddam-khoso.firebaseapp.com',
    storageBucket: 'saddam-khoso.firebasestorage.app',
    measurementId: 'G-FTXPK86ZVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqp9lQZDtSPJOfPhToeysDSiPAFSIdEXQ',
    appId: '1:83503088349:android:1d60272dc4f5fea991d134',
    messagingSenderId: '83503088349',
    projectId: 'saddam-khoso',
    storageBucket: 'saddam-khoso.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLdtDs1cnAVFBA_bblfk8MVG96Yp_gYt8',
    appId: '1:83503088349:ios:dbf7913891401a8891d134',
    messagingSenderId: '83503088349',
    projectId: 'saddam-khoso',
    storageBucket: 'saddam-khoso.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjAD9heDAoOXO9MfrT9TePQM0Pya5bunI',
    appId: '1:83503088349:web:884337083cf12e6691d134',
    messagingSenderId: '83503088349',
    projectId: 'saddam-khoso',
    authDomain: 'saddam-khoso.firebaseapp.com',
    storageBucket: 'saddam-khoso.firebasestorage.app',
    measurementId: 'G-CGBNDJD1RL',
  );
}
